env:
  SLACK_CHANNEL: team-lang-java-notifs
  SLACK_USERNAME: Dogfood build action
jobs:
  dogfood_merge:
    name: Update dogfood branch
    permissions:
      id-token: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: secrets
      name: get secrets
      uses: SonarSource/vault-action-wrapper@d1c1ab4ca5ad07fd9cdfe1eff038a39673dfca64
      with:
        secrets: 'development/kv/data/slack webhook | SLACK_WEBHOOK;

          development/github/token/{REPO_OWNER_NAME_DASH}-dogfood-merge token | dogfood_token;

          '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).dogfood_token }}
      id: dogfood
      name: git octopus step
      uses: SonarSource/gh-action_dogfood_merge@v1
      with:
        dogfood-branch: dogfood-on-peach
    - continue-on-error: true
      name: Get the name of the dogfood branch and its HEAD SHA1
      run: echo "The dogfood branch was `${{ steps.dogfood.outputs.dogfood-branch
        }}` and its HEAD SHA1 was `${{ steps.dogfood.outputs.sha1 }}`"
    - continue-on-error: true
      env:
        SLACK_OVERRIDE_MESSAGE: 'Dogfood build for `${{ steps.dogfood.outputs.sha1
          }}`: *successful*'
        SLACK_WEBHOOK: ${{ fromJSON(steps.secrets.outputs.vault).SLACK_WEBHOOK }}
      name: Notify success on Slack
      uses: Ilshidur/action-slack@1.6.2
      with:
        args: Succeed to build dogfood branch
    - continue-on-error: true
      env:
        SLACK_OVERRIDE_MESSAGE: 'Dogfood build for `${{ steps.dogfood.outputs.sha1
          }}`: *failed*, see the logs at https://github.com/SonarSource/sonar-java/actions'
        SLACK_WEBHOOK: ${{ fromJSON(steps.secrets.outputs.vault).SLACK_WEBHOOK }}
      if: failure()
      name: Notify failures on Slack
      uses: Ilshidur/action-slack@1.6.2
      with:
        args: Fail to build dogfood branch
name: dogfood merge
on:
  repository_dispatch:
    types: trigger-ga___dogfood.yml
