jobs:
  release:
    permissions:
      contents: write
      id-token: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@v5
    with:
      mavenCentralSync: true
      publishToBinaries: true
      slackChannel: team-lang-java-notifs
name: sonar-release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
